"use client";
/* eslint-disable @next/next/no-img-element -- QR data URLs and local blob previews cannot use the Next image optimizer. */
import QRCode from "qrcode";
import { useCallback, useEffect, useRef, useState } from "react";
import { createPhotoHandoff, photoHandoffStatus } from "./handoff-actions";
import { createBrowserSupabaseClient } from "@/lib/supabase/client";
import { profilePhotoPath, profilePhotoSourceError } from "./profile-photo-contract";
import { phonePhotoStageIsBusy, type PhonePhotoStage } from "./phone-photo-state";
import { attachNativePhotoChangeListener, isSupportedPhonePhoto } from "./phone-photo-selection";
import { cameraUnavailableMessage, captureCameraFrame, frontCameraConstraints, stopCameraStream } from "./phone-camera";

type HandoffProps = { profileId: string; onCompleted: (url: string) => void };

export function PhotoHandoff({ profileId, onCompleted }: HandoffProps) {
  const [qr, setQr] = useState(""); const [token, setToken] = useState(""); const [error, setError] = useState(""); const [expired, setExpired] = useState(false);
  async function start() { setError(""); setExpired(false); const result = await createPhotoHandoff(); if (!result.success) return setError(result.error); setToken(result.token); setQr(await QRCode.toDataURL(result.url)); }
  const refreshPhoto = useCallback(async () => { const { data } = await createBrowserSupabaseClient().storage.from("profile-photos").createSignedUrl(profilePhotoPath(profileId), 3600); if (data?.signedUrl) onCompleted(data.signedUrl); }, [onCompleted, profileId]);
  useEffect(() => { if (!token) return; const timer = setInterval(async () => { const result = await photoHandoffStatus(token); if (result.state === "completed") { clearInterval(timer); setToken(""); setQr(""); await refreshPhoto(); } else if (result.state !== "active") { clearInterval(timer); setToken(""); setQr(""); setExpired(true); } }, 5000); return () => clearInterval(timer); }, [refreshPhoto, token]);
  return <div className="mt-3"><button type="button" onClick={start} className="h-10 rounded-md bg-white px-3 text-sm font-semibold text-brand-primary ring-1 ring-border">{qr ? "Start a new phone handoff" : "Take photo on phone"}</button>{qr ? <div className="mt-3"><img src={qr} alt="Scan to take your profile photo on your phone" className="size-44"/><p className="mt-2 text-xs text-text-muted">Scan this code with your phone. This secure link expires in 10 minutes.</p><button type="button" onClick={refreshPhoto} className="mt-2 text-xs font-semibold text-brand-primary underline">Refresh photo status</button></div> : null}{expired ? <p role="status" className="mt-3 text-sm text-text-muted">This phone handoff expired. Start a new one to continue.</p> : null}{error ? <p role="alert" className="mt-3 text-sm text-danger-strong">{error}</p> : null}</div>;
}

export function PhonePhotoUpload({ token }: { token: string }) {
  const [image, setImage] = useState<Blob | null>(null); const [preview, setPreview] = useState(""); const [message, setMessage] = useState(""); const [stage, setStage] = useState<PhonePhotoStage>("initial");
  const video = useRef<HTMLVideoElement>(null); const stream = useRef<MediaStream | null>(null); const libraryInput = useRef<HTMLInputElement>(null);
  const stopCamera = useCallback(() => { stopCameraStream(stream.current); stream.current = null; }, []);
  useEffect(() => () => { if (preview) URL.revokeObjectURL(preview); stopCamera(); }, [preview, stopCamera]);
  const prepare = useCallback((file: File) => { const sourceError = profilePhotoSourceError(file); if (sourceError) { setStage("error"); setMessage(sourceError); return; } setStage("processing"); setMessage(""); const nextPreview = URL.createObjectURL(file); setImage(file); setPreview((current) => { if (current) URL.revokeObjectURL(current); return nextPreview; }); setStage("preview"); }, []);
  const receiveLibraryFile = useCallback((file: File | null) => { if (!file) return; if (libraryInput.current) libraryInput.current.value = ""; if (!isSupportedPhonePhoto(file)) { setStage("error"); setMessage("Choose a photo from your camera or library."); return; } prepare(file); }, [prepare]);
  useEffect(() => { const input = libraryInput.current; return input ? attachNativePhotoChangeListener(input, receiveLibraryFile) : undefined; }, [receiveLibraryFile]);
  useEffect(() => { if (stage !== "camera_live" || !video.current || !stream.current) return; video.current.srcObject = stream.current; void video.current.play(); }, [stage]);
  async function startCamera() { if (!window.isSecureContext) return setMessage(cameraUnavailableMessage(false, true)); if (!navigator.mediaDevices?.getUserMedia) return setMessage(cameraUnavailableMessage(true, false)); setStage("requesting_camera"); setMessage(""); try { stopCamera(); stream.current = await navigator.mediaDevices.getUserMedia(frontCameraConstraints); setStage("camera_live"); } catch { setStage("error"); setMessage(cameraUnavailableMessage(true, true)); } }
  async function takeCameraPhoto() { if (!video.current) return; setStage("processing"); try { const frame = await captureCameraFrame(video.current); stopCamera(); prepare(new File([frame], "camera.webp", { type: "image/webp" })); } catch (error) { stopCamera(); setStage("error"); setMessage(error instanceof Error ? error.message : "The photo could not be captured. Please try again."); } }
  async function upload() { if (!image) return; setStage("uploading"); setMessage(""); try { const response = await fetch(`/api/onboarding/photo-handoff/${encodeURIComponent(token)}`, { method: "POST", headers: { "content-type": image.type }, body: image }); const result = await response.json() as { success: boolean; error?: string }; if (result.success) { stopCamera(); setStage("completed"); } else { setStage("error"); setMessage(result.error ?? "The photo could not be uploaded. Please try again."); } } catch { setStage("error"); setMessage("The photo could not be uploaded. Please try again."); } }
  function cancelCamera() { stopCamera(); setStage("initial"); }
  function clearPreview() { setImage(null); setPreview(""); }
  const busy = phonePhotoStageIsBusy(stage) || stage === "requesting_camera";
  const pickerClass = `inline-flex h-11 items-center justify-center rounded-md px-4 text-sm font-bold ${busy ? "pointer-events-none opacity-60" : ""}`;
  return <main className="mx-auto min-h-screen max-w-md p-6"><p className="font-heading text-xs font-extrabold uppercase tracking-widest text-brand-secondary">Resonate</p><h1 className="font-heading mt-2 text-2xl font-bold text-text-primary">Add your profile photo</h1>{stage === "completed" ? <p role="status" className="mt-5 text-sm leading-6 text-success-strong">Photo added successfully.<br />You can return to your computer.</p> : <><p className="mt-2 text-sm text-text-muted">Take a photo or choose one from your library.</p><input id="phone-library-input" ref={libraryInput} className="sr-only" type="file" accept="image/*" disabled={busy}/>{stage === "camera_live" ? <div className="mt-6"><video ref={video} autoPlay playsInline muted className="aspect-[3/4] w-full rounded-md bg-black object-cover"/><div className="mt-3 flex gap-2"><button type="button" onClick={takeCameraPhoto} className="h-11 rounded-md bg-brand-primary px-4 text-sm font-bold text-white">Take Photo</button><button type="button" onClick={cancelCamera} className="h-11 rounded-md border border-border bg-white px-4 text-sm font-bold text-brand-primary">Cancel</button></div></div> : <div className="mt-6 flex flex-wrap gap-2"><button type="button" onClick={startCamera} disabled={busy} className="h-11 rounded-md bg-brand-primary px-4 text-sm font-bold text-white disabled:opacity-60">Take Photo</button><label htmlFor="phone-library-input" aria-disabled={busy} className={`${pickerClass} border border-border bg-white text-brand-primary`}>Choose from Library</label></div>}{stage === "processing" ? <p role="status" className="mt-5 text-sm text-text-muted">Preparing your photo...</p> : null}{preview ? <div className="mt-5"><img src={preview} alt="Selected profile photo preview" className="size-40 rounded-full object-cover"/><div className="mt-3 flex flex-wrap gap-2"><button type="button" onClick={upload} disabled={busy} className="h-11 rounded-md bg-sidebar-active px-4 text-sm font-bold text-white disabled:opacity-60">{stage === "uploading" ? "Uploading..." : "Use this photo"}</button><button type="button" onClick={() => { clearPreview(); void startCamera(); }} disabled={busy} className="h-11 rounded-md border border-border bg-white px-4 text-sm font-bold text-brand-primary">Retake</button><label htmlFor="phone-library-input" onClick={clearPreview} aria-disabled={busy} className={`${pickerClass} border border-border bg-white text-brand-primary`}>Choose another</label></div></div> : null}{message ? <p role="alert" className="mt-5 text-sm text-danger-strong">{message}</p> : null}</>}</main>;
}
