"use client";

import { useState, useTransition } from "react";
import { updateOwnProfile } from "./management";
import { formatPhoneInput } from "./phone";
import { ProfilePhotoField } from "./profile-photo-field";

export function ProfileEdit({ profileId, firstName, lastName, phone, email, campus, hasPhoto, photoUrl }: { profileId: string; firstName: string; lastName: string; phone: string; email: string; campus: string; hasPhoto: boolean; photoUrl: string | null }) {
  const [pending, startTransition] = useTransition(); const [message, setMessage] = useState("");
  return <form className="grid max-w-xl gap-4 rounded-lg border border-border bg-surface p-6" onSubmit={(event) => { event.preventDefault(); setMessage(""); const data = new FormData(event.currentTarget); startTransition(async () => { const result = await updateOwnProfile(data); setMessage("error" in result ? result.error : "Profile saved."); }); }}><label className="grid gap-1.5 text-sm font-medium">First name<input name="firstName" defaultValue={firstName} required className="min-h-10 rounded-md border border-border bg-white px-3" /></label><label className="grid gap-1.5 text-sm font-medium">Last name<input name="lastName" defaultValue={lastName} required className="min-h-10 rounded-md border border-border bg-white px-3" /></label><label className="grid gap-1.5 text-sm font-medium">Phone<input name="phone" defaultValue={formatPhoneInput(phone)} required inputMode="tel" className="min-h-10 rounded-md border border-border bg-white px-3" /></label><label className="grid gap-1.5 text-sm font-medium">Email<input value={email} readOnly className="min-h-10 cursor-not-allowed rounded-md border border-border bg-surface-muted px-3 text-text-muted" /></label><label className="grid gap-1.5 text-sm font-medium">Campus<input value={campus} readOnly className="min-h-10 cursor-not-allowed rounded-md border border-border bg-surface-muted px-3 text-text-muted" /></label><ProfilePhotoField profileId={profileId} hasPhoto={hasPhoto} photoUrl={photoUrl} onSaved={() => setMessage("Profile photo saved.")} />{message ? <p role="status" className="text-sm text-text-muted">{message}</p> : null}<button type="submit" disabled={pending} className="min-h-10 rounded-md bg-brand-primary px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{pending ? "Saving..." : "Save profile"}</button></form>;
}
