"use client";

import { Plus, Save } from "lucide-react";
import { useState, useTransition } from "react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { formatPhoneInput } from "@/features/onboarding/phone";
import { createPeopleInvitations } from "./invitation-actions";
import { invitationSuccessMessage } from "./invitation-messages";
import { isGroupedInvitationRole, type InvitationPerson, validateInvitation } from "./invitation-validation";

type Campus = { id: string; name: string };
const types = ["admin", "super_admin", "campus_lead", "author", "coach", "counselor", "couple"] as const;
const empty = (): InvitationPerson => ({ firstName: "", lastName: "", email: "", phone: "" });

export function InvitePeopleForm({ campuses, isSuperAdmin }: { campuses: Campus[]; isSuperAdmin: boolean }) {
  const [open, setOpen] = useState(false); const [role, setRole] = useState("admin"); const [campus, setCampus] = useState(""); const [tab, setTab] = useState("person-1");
  const [people, setPeople] = useState<[InvitationPerson, InvitationPerson]>([empty(), empty()]); const [submitted, setSubmitted] = useState(false); const [serverError, setServerError] = useState<string | null>(null); const [success, setSuccess] = useState<string | null>(null); const [pending, startTransition] = useTransition();
  const grouped = isGroupedInvitationRole(role); const couple = role === "couple"; const errors = validateInvitation(role, campus, people); const valid = !Object.keys(errors).length; const available = types.filter((type) => type !== "super_admin" || isSuperAdmin);
  const reset = () => { setRole("admin"); setCampus(""); setTab("person-1"); setPeople([empty(), empty()]); setSubmitted(false); setServerError(null); setSuccess(null); };
  const update = (index: number, key: keyof InvitationPerson, value: string) => setPeople((current) => current.map((person, i) => i === index ? { ...person, [key]: key === "phone" ? formatPhoneInput(value) : value } : person) as [InvitationPerson, InvitationPerson]);
  const submit = () => { setSubmitted(true); if (!valid) { if (Object.keys(errors).some((key) => key.endsWith("1"))) setTab("person-2"); return; } const data = new FormData(); data.set("role", role); data.set("campusId", campus); people.slice(0, grouped ? 2 : 1).forEach((person, index) => { data.set(`firstName${index}`, person.firstName); data.set(`lastName${index}`, person.lastName); data.set(`email${index}`, person.email); if (couple) data.set(`phone${index}`, person.phone ?? ""); }); startTransition(async () => { const result = await createPeopleInvitations(data); if ("error" in result) { setServerError(result.error); return; } setOpen(false); setSuccess(invitationSuccessMessage(result)); }); };
  return <><button type="button" onClick={() => { reset(); setOpen(true); }} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-brand-primary px-4 py-2 text-sm font-bold text-white"><Plus className="size-4" />Invite People</button>{success ? <p role="status" className="mt-3 text-sm text-success-strong">{success}</p> : null}<Sheet open={open} onOpenChange={(next) => { if (!next) reset(); setOpen(next); }}><SheetContent side="right" className="overflow-y-auto bg-sidebar p-0"><SheetHeader className="border-b border-border px-6 py-5"><SheetTitle>Invite People</SheetTitle><SheetDescription>Create invitations and send secure account emails.</SheetDescription></SheetHeader><form noValidate className="grid gap-5 p-6" onSubmit={(event) => { event.preventDefault(); submit(); }}><label className="grid gap-1.5 text-sm font-medium">Invite type<Select value={role} onValueChange={(value) => { setRole(value); setTab("person-1"); if (!isGroupedInvitationRole(value)) setPeople((current) => [current[0], empty()]); }}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent>{available.map((type) => <SelectItem key={type} value={type}>{type.replace("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase())}</SelectItem>)}</SelectContent></Select></label><label className="grid gap-1.5 text-sm font-medium">Campus<Select value={campus} onValueChange={setCampus}><SelectTrigger className={submitted && errors.campus ? "border-error-strong" : ""}><SelectValue placeholder="Select an active Campus" /></SelectTrigger><SelectContent>{campuses.map((item) => <SelectItem key={item.id} value={item.id}>{item.name}</SelectItem>)}</SelectContent></Select>{submitted && errors.campus ? <Error text={errors.campus} /> : null}</label>{grouped ? <p className="text-sm text-text-muted">Each person receives a separate account invitation.</p> : null}{grouped ? <Tabs value={tab} onValueChange={setTab}><TabsList className="w-full"><TabsTrigger value="person-1" className="flex-1">{couple ? "Partner 1" : "First Person"}</TabsTrigger><TabsTrigger value="person-2" className="flex-1">{couple ? "Partner 2" : "Second Person"}</TabsTrigger></TabsList><TabsContent value="person-1"><Person index={0} person={people[0]} errors={errors} submitted={submitted} update={update} showPhone={couple} couple={couple} /></TabsContent><TabsContent value="person-2"><Person index={1} person={people[1]} errors={errors} submitted={submitted} update={update} showPhone={couple} couple={couple} /></TabsContent></Tabs> : <Person index={0} person={people[0]} errors={errors} submitted={submitted} update={update} standalone />}{serverError ? <Error text={serverError} /> : null}<button disabled={!valid || pending} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-md bg-brand-primary px-4 py-2 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-60"><Save className="size-4" />{pending ? "Sending..." : "Send invitation"}</button></form></SheetContent></Sheet></>;
}

function Person({ index, person, errors, submitted, update, standalone, showPhone, couple }: { index: number; person: InvitationPerson; errors: Record<string, string>; submitted: boolean; update: (index: number, key: keyof InvitationPerson, value: string) => void; standalone?: boolean; showPhone?: boolean; couple?: boolean }) {
  const title = standalone ? "Invitee Details" : couple ? `Partner ${index + 1}` : index ? "Second Person Details" : "First Person Details"; const fields = showPhone ? ["firstName", "lastName", "email", "phone"] as const : ["firstName", "lastName", "email"] as const;
  return <section className="grid gap-3 rounded-md border border-border p-4"><h3 className="whitespace-nowrap text-sm font-semibold">{title}</h3>{fields.map((key) => { const id = `${key}${index}`; const error = submitted ? errors[id] : undefined; const placeholder = key === "firstName" ? "First name" : key === "lastName" ? "Last name" : key === "email" ? "Email" : "Phone"; return <div key={id} className="grid gap-1"><input value={person[key] ?? ""} onChange={(event) => update(index, key, event.target.value)} aria-invalid={Boolean(error)} placeholder={placeholder} type={key === "email" ? "email" : "text"} inputMode={key === "phone" ? "tel" : undefined} autoComplete={key === "phone" ? "tel" : undefined} className={`min-h-10 rounded-md border bg-white px-3 text-sm ${error ? "border-error-strong" : "border-border"}`} />{error ? <Error text={error} /> : null}</div>; })}</section>;
}
function Error({ text }: { text: string }) { return <p role="alert" className="text-sm text-error-strong">{text}</p>; }
