"use client";

import Image from "next/image";
import Link from "next/link";
import { Network, UserRound, X } from "lucide-react";
import { Dialog } from "radix-ui";
import { useState } from "react";

import type { OperationalHierarchy, OperationalHierarchyTeam } from "./operational-hierarchy-model";

const labels = { campus_lead: "Campus Lead", coach: "Coach", counselor: "Counselor" };

function TeamCard({ team, currentId, compact = false }: { team: OperationalHierarchyTeam; currentId: string; compact?: boolean }) {
  const current = team.id === currentId;
  return <Link href={`/people/${team.id}`} aria-label={`View ${labels[team.role]} ${team.name}`} className={`flex min-w-0 items-center gap-3 rounded-lg border bg-white p-3 text-left shadow-sm transition hover:bg-surface-muted ${current ? "border-brand-primary bg-sidebar-accent" : "border-border"} ${compact ? "" : "w-full sm:max-w-md"}`}><span className="grid size-10 shrink-0 place-items-center overflow-hidden rounded-full bg-surface-muted text-text-muted">{team.photoUrl ? <Image src={team.photoUrl} alt="" width={40} height={40} unoptimized className="size-full object-cover" /> : <UserRound className="size-5" aria-hidden="true" />}</span><span className="min-w-0"><span className="block text-xs font-semibold uppercase tracking-wide text-brand-secondary">{labels[team.role]}</span><span className="block truncate font-heading text-sm font-bold text-text-primary">{team.name}</span><span className="block truncate text-xs text-text-muted">{team.campus ?? "Campus not assigned"}</span>{current ? <span className="sr-only">Current team</span> : null}</span></Link>;
}

export function OperationalHierarchyDialog({ hierarchy, currentId }: { hierarchy: OperationalHierarchy; currentId: string }) {
  const [open, setOpen] = useState(false);
  return <Dialog.Root open={open} onOpenChange={setOpen}><Dialog.Trigger asChild><button type="button" className="inline-flex min-h-9 items-center gap-2 rounded-md bg-brand-primary px-3 py-1.5 text-sm font-semibold text-white hover:bg-brand-primary/90"><Network className="size-4" aria-hidden="true" />View Hierarchy</button></Dialog.Trigger><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-black/50" /><Dialog.Content className="fixed inset-x-3 top-1/2 z-50 flex max-h-[90vh] -translate-y-1/2 flex-col rounded-xl bg-background shadow-xl sm:left-1/2 sm:right-auto sm:w-[min(760px,calc(100vw-3rem))] sm:-translate-x-1/2"><div className="relative shrink-0 border-b border-border px-6 py-5"><Dialog.Title className="font-heading text-xl font-bold text-text-primary">Operational Hierarchy</Dialog.Title><Dialog.Description className="mt-1 text-sm text-text-muted">Campus Lead → Coaches → Counselors</Dialog.Description><Dialog.Close className="absolute right-4 top-4 grid size-9 place-items-center rounded-md text-text-muted hover:bg-surface-muted"><X className="size-4" /><span className="sr-only">Close</span></Dialog.Close></div><div className="min-h-0 overflow-y-auto p-5 sm:p-7">{hierarchy.campusLeads.map((lead) => <section key={lead.id} className="mb-8 last:mb-0"><TeamCard team={lead} currentId={currentId} /><section className="mt-6"><h2 className="font-heading text-base font-bold text-text-primary">Coaches ({lead.coaches.length})</h2><div className="mt-3 space-y-4">{lead.coaches.map((coach) => <section key={coach.id} className="rounded-lg border border-border bg-surface-muted/50 p-4"><TeamCard team={coach} currentId={currentId} compact /><section className="ml-4 mt-4 border-l-2 border-border pl-4"><h3 className="text-sm font-semibold text-text-primary">Counselors ({coach.counselors.length})</h3>{coach.counselors.length ? <div className="mt-3 space-y-2">{coach.counselors.map((counselor) => <TeamCard key={counselor.id} team={counselor} currentId={currentId} compact />)}</div> : <p className="mt-2 text-sm text-text-muted">No counselors assigned</p>}</section></section>)}</div></section></section>)}<section className="rounded-lg border border-border bg-surface-muted p-4 text-sm text-text-muted"><h2 className="font-heading font-bold text-text-primary">About this view</h2><p className="mt-1">Shows operational hierarchy only: Campus Lead → Coaches → Counselors. Couples are not included, and Counselors appear beneath their Coach. Selecting a team opens its detail page.</p></section></div></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
