"use client";

import { type ReactNode, useState, useTransition } from "react";
import { Pencil, Save, UserRoundCheck, UsersRound } from "lucide-react";
import { useRouter } from "next/navigation";

import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

import { assignCoach, assignCoachToCampusLead, assignCounselor, assignCounselorToCoach, assignCoupleAsCampusLead, assignCoupleTeam, updatePeopleDetail } from "./detail-actions";
import { actionLabel, availablePeopleDetailActions, campusLeadCoachAssignmentUnavailable, campusLeadCoachEmptyMessage, counselingTeamsEmptyMessage, counselingTeamsUnavailable, counselorAssignmentLabel, teamOptionLabel, type PeopleDetailAction, type PeopleDetailActionContext } from "./detail-actions-model";
import type { PeopleDetail } from "./detail-model";
import { canDisplayCampus } from "../settings/campus-model";

type ActionResult = { error: string } | { success: true };
type Mutation = (formData: FormData) => Promise<ActionResult>;

function ActionButton({ action, onClick, compact = false, disabled = false }: { action: PeopleDetailAction; onClick: () => void; compact?: boolean; disabled?: boolean }) {
  const Icon = action === "edit" ? Pencil : action.includes("counselor") ? UserRoundCheck : UsersRound;
  return <button type="button" aria-label={actionLabel(action)} onClick={onClick} disabled={disabled} className={`inline-flex min-h-9 ${compact ? "w-full" : "w-auto"} shrink-0 items-center justify-center gap-2 rounded-md bg-brand-primary px-3 py-1.5 text-sm font-semibold text-white transition hover:bg-brand-primary/90 focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-brand-primary disabled:cursor-not-allowed disabled:opacity-60`}><Icon className="size-4" aria-hidden="true" />{actionLabel(action)}</button>;
}

function CampusField({ detail, campuses }: { detail: PeopleDetail; campuses: PeopleDetailActionContext["campuses"] }) {
  return <div className="grid gap-1.5"><label htmlFor="people-campus" className="text-sm font-medium text-text-primary">Campus</label><Select name="campusId" defaultValue={detail.campusId ?? "__none__"}><SelectTrigger id="people-campus"><SelectValue placeholder="Select a campus" /></SelectTrigger><SelectContent><SelectItem value="__none__">No campus assigned</SelectItem>{campuses.filter((campus) => canDisplayCampus(campus, detail.campusId, campus.id)).map((campus) => <SelectItem key={campus.id} value={campus.id} disabled={!campus.active}>{campus.active ? campus.name : `${campus.name} (Inactive)`}</SelectItem>)}</SelectContent></Select></div>;
}

function EditForm({ detail, context, submit, onSuccess }: { detail: PeopleDetail; context: PeopleDetailActionContext; submit: Mutation; onSuccess: () => void }) {
  const profile = detail.kind === "profile" ? detail.member : null;
  return <ActionForm submit={submit} buttonLabel="Save changes" onSuccess={onSuccess}><input type="hidden" name="recordId" value={detail.id} />{detail.kind === "group" ? <label className="grid gap-1.5 text-sm font-medium text-text-primary">Team name<input required name="name" maxLength={120} defaultValue={detail.name} className="min-h-10 rounded-md border border-border bg-white px-3 text-sm text-text-primary focus:outline-2 focus:outline-offset-2 focus:outline-brand-primary" /></label> : <><input type="hidden" name="name" value={detail.name} /><label className="grid gap-1.5 text-sm font-medium text-text-primary">First name<input required name="firstName" maxLength={80} defaultValue={profile!.firstName} className="min-h-10 rounded-md border border-border bg-white px-3 text-sm text-text-primary focus:outline-2 focus:outline-offset-2 focus:outline-brand-primary" /></label><label className="grid gap-1.5 text-sm font-medium text-text-primary">Last name<input required name="lastName" maxLength={80} defaultValue={profile!.lastName} className="min-h-10 rounded-md border border-border bg-white px-3 text-sm text-text-primary focus:outline-2 focus:outline-offset-2 focus:outline-brand-primary" /></label></>}<CampusField detail={detail} campuses={context.campuses} /></ActionForm>;
}

function AssignmentForm({ detail, action, context, submit, onSuccess }: { detail: PeopleDetail; action: PeopleDetailAction; context: PeopleDetailActionContext; submit: Mutation; onSuccess: () => void }) {
  const genericCoupleAssignment = detail.kind === "group" && detail.type === "couples" && (action === "assign-team" || action === "reassign-team");
  const counselorAssignment = !genericCoupleAssignment && (action === "assign-team" || action === "reassign-team");
  const coachAssignment = action === "assign-coach" || action === "reassign-coach" || action === "assign-campus-lead-coach";
  const counselorForCoach = action === "assign-counselor";
  const teams = genericCoupleAssignment ? context.eligibleCounselingTeams : action === "assign-campus-lead-coach" ? context.campusLeadCoachTeams : coachAssignment ? context.coachTeams : context.counselorTeams;
  const current = genericCoupleAssignment ? context.currentCoupleTeam : coachAssignment ? context.currentCoachTeam : context.currentCounselorTeam;
  const defaultValue = current?.id ?? "";
  const [selectedValue, setSelectedValue] = useState(genericCoupleAssignment ? (defaultValue ? `group:${defaultValue}` : "") : defaultValue);
  return <ActionForm submit={submit} buttonLabel={actionLabel(action)} onSuccess={onSuccess}><input type="hidden" name="recordId" value={detail.id} />{!genericCoupleAssignment && counselorAssignment ? <p className="rounded-md bg-surface-muted px-3 py-2 text-sm text-text-muted">Current counselor: <span className="font-semibold text-text-primary">{counselorAssignmentLabel(context.currentCounselorTeam)}</span></p> : counselorForCoach && context.currentCounselorTeams.length ? <p className="rounded-md bg-surface-muted px-3 py-2 text-sm text-text-muted">Current Counselors: <span className="font-semibold text-text-primary">{context.currentCounselorTeams.map((team) => teamOptionLabel(team)).join(", ")}</span></p> : !genericCoupleAssignment && current ? <p className="rounded-md bg-surface-muted px-3 py-2 text-sm text-text-muted">Current assignment: <span className="font-semibold text-text-primary">{teamOptionLabel(current)}</span></p> : null}<div className="grid min-w-0 gap-1.5"><label htmlFor="people-target-team" className="text-sm font-medium text-text-primary">{genericCoupleAssignment ? "Who is counseling this Couple?" : counselorAssignment || counselorForCoach ? "Counselor team" : "Coach team"}</label><input type="hidden" name="targetGroupId" value={selectedValue} /><Select required value={selectedValue} onValueChange={setSelectedValue}><SelectTrigger id="people-target-team" className="min-w-0 w-full"><SelectValue placeholder={genericCoupleAssignment ? "Select a counseling team" : counselorAssignment || counselorForCoach ? "Select a Counselor team" : "Select an assignment target"} /></SelectTrigger><SelectContent className="w-[var(--radix-select-trigger-width)] max-w-full">{teams.map((team) => <SelectItem key={team.id} value={genericCoupleAssignment ? `group:${team.id}` : team.id} className="min-w-0"><span className="block min-w-0 truncate">{teamOptionLabel(team, genericCoupleAssignment)}</span></SelectItem>)}</SelectContent></Select></div></ActionForm>;
}

function ActionForm({ children, submit, buttonLabel, onSuccess }: { children: ReactNode; submit: Mutation; buttonLabel: string; onSuccess: () => void }) {
  const router = useRouter();
  const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  return <form className="grid gap-4" onSubmit={(event) => { event.preventDefault(); setError(null); const formData = new FormData(event.currentTarget); if (formData.get("campusId") === "__none__") formData.set("campusId", ""); startTransition(async () => { const result = await submit(formData); if ("error" in result) { setError(result.error); return; } onSuccess(); router.refresh(); }); }}>{children}{error ? <p role="alert" className="text-sm text-error-strong">{error}</p> : null}<div className="flex justify-end gap-3"><button type="button" onClick={onSuccess} disabled={pending} className="min-h-10 rounded-md px-3 text-sm font-semibold text-text-muted transition hover:bg-surface-muted hover:text-text-primary">Cancel</button><button type="submit" disabled={pending} className="inline-flex min-h-10 items-center justify-center gap-2 rounded-md bg-brand-primary px-4 py-2 text-sm font-semibold text-white transition hover:bg-brand-primary/90 disabled:cursor-not-allowed disabled:opacity-60"><Save className="size-4" aria-hidden="true" />{pending ? "Saving..." : buttonLabel}</button></div></form>;
}

export function PeopleDetailActions({ detail, context, hideEdit = false, onlyEdit = false, compact = false }: { detail: PeopleDetail; context: PeopleDetailActionContext; hideEdit?: boolean; onlyEdit?: boolean; compact?: boolean }) {
  const [openAction, setOpenAction] = useState<PeopleDetailAction | null>(null);
  const actions = availablePeopleDetailActions(detail, context).filter((action) => !(hideEdit && action === "edit") && !(onlyEdit && action !== "edit"));
  const campusLeadCoachUnavailable = detail.kind === "group" && detail.type === "campus_leads" && campusLeadCoachAssignmentUnavailable(context.campusLeadCoachTeams);
  const counselingTeamsUnavailableForCouple = detail.kind === "group" && detail.type === "couples" && context.coupleAssignmentReady && counselingTeamsUnavailable(context.eligibleCounselingTeams);
  const submit = openAction === "edit" ? updatePeopleDetail : openAction === "assign-team" || openAction === "reassign-team" ? context.mode === "campus_lead" ? assignCoupleAsCampusLead : assignCoupleTeam : openAction === "assign-campus-lead-coach" ? assignCoachToCampusLead : openAction === "assign-counselor" ? assignCounselorToCoach : openAction?.includes("coach") ? assignCoach : assignCounselor;
  return <><div className={`flex flex-wrap gap-2 ${compact ? "w-full" : ""}`}>{actions.map((action) => <ActionButton key={action} action={action} compact={compact} disabled={action === "assign-campus-lead-coach" && campusLeadCoachUnavailable || (action === "assign-team" || action === "reassign-team") && counselingTeamsUnavailableForCouple} onClick={() => setOpenAction(action)} />)}</div>{campusLeadCoachUnavailable && actions.includes("assign-campus-lead-coach") ? <p className="text-sm text-text-muted">{campusLeadCoachEmptyMessage(detail.campus)}</p> : null}{counselingTeamsUnavailableForCouple && actions.some((action) => action === "assign-team" || action === "reassign-team") ? <p className="text-sm text-text-muted">{counselingTeamsEmptyMessage()}</p> : null}<Sheet open={openAction !== null} onOpenChange={(open) => setOpenAction(open ? openAction : null)}><SheetContent side="right" className="overflow-y-auto p-0"><SheetHeader className="border-b border-border px-6 py-5"><SheetTitle>{openAction ? actionLabel(openAction) : "People action"}</SheetTitle><SheetDescription>{openAction === "edit" ? "Update the safe fields available for this record." : context.mode === "campus_lead" ? "Choose an eligible person or team for this care-team relationship." : "Choose an eligible team for this assignment."}</SheetDescription></SheetHeader><div className="p-6">{openAction === "edit" ? <EditForm detail={detail} context={context} submit={submit} onSuccess={() => setOpenAction(null)} /> : openAction ? <AssignmentForm detail={detail} action={openAction} context={context} submit={submit} onSuccess={() => setOpenAction(null)} /> : null}</div></SheetContent></Sheet></>;
}
