import { Search, Users } from "lucide-react";
import Link from "next/link";
import type { ReactNode } from "react";

import { Badge } from "@/components/ui/badge";
import { Card } from "@/components/ui/card";

import type { PeopleFilter, PeopleRecord } from "./types";

const labels: Record<PeopleFilter, string> = { all: "All", couples: "Couples", coaches: "Coaches", counselors: "Counselors", admins: "Admins", authors: "Authors" };

function roleLabel(role: string) { return role.replace("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
function dateLabel(value: string) { return new Intl.DateTimeFormat("en", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)); }
function cell(value: string | null) { return value ?? "—"; }

function Roles({ roles }: { roles: string[] }) { return <div className="flex flex-wrap gap-1">{roles.map((role) => <Badge key={role} className="bg-info-soft text-info-strong">{roleLabel(role)}</Badge>)}</div>; }

function RecordCard({ record }: { record: PeopleRecord }) {
  return <Card className="p-5">
    <div className="flex items-start justify-between gap-3"><div><p className="font-heading font-bold text-text-primary">{record.name}</p><p className="mt-1 text-xs text-text-muted">{labels[record.type]}</p></div><Link href={`/people/${record.id}`} className="text-sm font-medium text-brand-primary hover:underline">View</Link></div>
    <div className="mt-4"><Roles roles={record.roles} /></div>
    <dl className="mt-4 grid grid-cols-2 gap-x-4 gap-y-3 text-sm"><div><dt className="text-xs text-text-muted">Campus</dt><dd className="mt-1 text-text-primary">{cell(record.campus)}</dd></div><div><dt className="text-xs text-text-muted">Counseling status</dt><dd className="mt-1 text-text-primary">{cell(record.counselingStatus)}</dd></div><div className="col-span-2"><dt className="text-xs text-text-muted">Assigned to</dt><dd className="mt-1 text-text-primary">{cell(record.assignedTo)}</dd></div></dl>
  </Card>;
}

export function PeoplePage({ records, filter, search, error, inviteAction }: { records: PeopleRecord[]; filter: PeopleFilter; search: string; error?: "unauthorized" | "unavailable"; inviteAction?: ReactNode }) {
  const noResults = search || filter !== "all";
  return <main id="people" className="mx-auto max-w-[1500px] p-5 sm:p-8 lg:p-10"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="font-heading text-xs font-extrabold uppercase tracking-widest text-brand-secondary">Admin workspace</p><h1 className="font-heading mt-1 text-2xl font-bold text-text-primary">People & Teams</h1><p className="mt-2 text-sm text-text-muted">People, operational teams, roles, and active counseling context.</p></div>{inviteAction}</div>
    <Card className="mt-7 p-5 sm:p-6"><form className="flex flex-col gap-4 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Search people and teams</span><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-text-muted" aria-hidden="true"/><input name="q" defaultValue={search} placeholder="Search names, teams, email, or campus" className="h-11 w-full rounded-md border border-border bg-white pl-10 pr-3 text-sm text-text-primary outline-none focus:border-brand-primary"/></label><button className="h-11 rounded-md bg-brand-primary px-4 text-sm font-bold text-white">Search</button></form><nav aria-label="People filters" className="mt-4 flex gap-2 overflow-x-auto pb-1">{(Object.keys(labels) as PeopleFilter[]).map((item) => <a key={item} href={`/people?filter=${item}${search ? `&q=${encodeURIComponent(search)}` : ""}`} className={item === filter ? "shrink-0 rounded-md bg-sidebar-accent px-3 py-2 text-sm font-bold text-sidebar-active" : "shrink-0 rounded-md bg-surface-muted px-3 py-2 text-sm text-text-muted hover:text-brand-primary"}>{labels[item]}</a>)}</nav></Card>
    {error ? <Card className="mt-7 p-8 text-center"><Users className="mx-auto size-8 text-text-muted" aria-hidden="true"/><h2 className="font-heading mt-4 text-lg font-bold text-text-primary">{error === "unauthorized" ? "Admin access is required" : "People & Teams is temporarily unavailable"}</h2><p className="mt-2 text-sm text-text-muted">{error === "unauthorized" ? "Sign in with an Admin or Super Admin account to view this workspace." : "Please try again shortly. No database details have been exposed."}</p></Card> : records.length === 0 ? <Card className="mt-7 p-8 text-center"><Users className="mx-auto size-8 text-text-muted" aria-hidden="true"/><h2 className="font-heading mt-4 text-lg font-bold text-text-primary">{noResults ? "No matching people or teams" : "No people or teams yet"}</h2><p className="mt-2 text-sm text-text-muted">{noResults ? "Adjust the search or filter to see other records." : "Records will appear here when they are added to the counseling workspace."}</p></Card> : <><div className="mt-7 grid gap-4 lg:hidden">{records.map((record) => <RecordCard key={`${record.type}-${record.id}`} record={record}/>)}</div><Card className="mt-7 hidden overflow-hidden lg:block"><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-surface-muted text-xs text-text-muted"><tr>{["Name / Team","Type","Roles","Campus","Counseling Status","Assigned To","Last Updated","Actions"].map((heading) => <th key={heading} className="whitespace-nowrap px-5 py-3 font-medium">{heading}</th>)}</tr></thead><tbody className="divide-y divide-border">{records.map((record) => <tr key={`${record.type}-${record.id}`}><td className="px-5 py-4 font-heading font-bold text-text-primary">{record.name}</td><td className="px-5 py-4 capitalize text-text-muted">{labels[record.type]}</td><td className="px-5 py-4"><Roles roles={record.roles}/></td><td className="px-5 py-4 text-text-muted">{cell(record.campus)}</td><td className="px-5 py-4 text-text-muted">{cell(record.counselingStatus)}</td><td className="px-5 py-4 text-text-muted">{cell(record.assignedTo)}</td><td className="px-5 py-4 whitespace-nowrap text-text-muted">{dateLabel(record.updatedAt)}</td><td className="px-5 py-4"><Link href={`/people/${record.id}`} className="font-medium text-brand-primary hover:underline">View</Link></td></tr>)}</tbody></table></div></Card></>}</main>;
}
