"use client";

import { useState, useTransition } from "react";
import { AlertTriangle, Trash2 } from "lucide-react";
import { useRouter } from "next/navigation";

import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { permanentlyDeletePerson, setPersonActive } from "./person-lifecycle-actions";

export function PersonLifecycle({ profileId, active, isSuperAdmin }: { profileId: string; active: boolean; isSuperAdmin: boolean }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [confirmation, setConfirmation] = useState(""); const [message, setMessage] = useState<string | null>(null); const [pending, start] = useTransition();
  const state = () => start(async () => { const data = new FormData(); data.set("profileId", profileId); const result = await setPersonActive(data, !active); if ("error" in result) setMessage(result.error); else router.refresh(); });
  const remove = () => start(async () => { const data = new FormData(); data.set("profileId", profileId); const result = await permanentlyDeletePerson(data); if ("error" in result) setMessage(result.error); else router.push("/people"); });
  return <div className="mt-5 flex flex-wrap gap-2 border-t border-border pt-5"><button type="button" onClick={state} disabled={pending} className="min-h-10 rounded-md border border-border px-3 text-sm font-semibold text-text-primary hover:bg-surface-muted disabled:opacity-60">{active ? "Deactivate" : "Reactivate"}</button>{isSuperAdmin ? <><button type="button" onClick={() => { setMessage(null); setOpen(true); }} className="inline-flex min-h-10 items-center gap-2 rounded-md border border-danger-strong/40 px-3 text-sm font-semibold text-danger-strong hover:bg-danger-soft"><Trash2 className="size-4" aria-hidden="true" />Permanently Delete</button><Sheet open={open} onOpenChange={setOpen}><SheetContent side="right" className="overflow-y-auto p-0"><SheetHeader className="border-b border-border px-6 py-5"><SheetTitle className="text-danger-strong">Permanently delete person</SheetTitle><SheetDescription>This action cannot be undone.</SheetDescription></SheetHeader><div className="grid gap-5 p-6"><div className="flex gap-3 rounded-md border border-danger-strong/25 bg-danger-soft p-4 text-sm text-danger-strong"><AlertTriangle className="size-5 shrink-0" aria-hidden="true" />Delete this disposable account permanently. Retained ministry history will block deletion.</div><label className="grid gap-2 text-sm font-medium">Type <span className="font-mono font-bold text-danger-strong">DELETE</span> to confirm<input value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="min-h-10 rounded-md border border-border px-3 font-mono" /></label>{message ? <p role="alert" className="text-sm text-danger-strong">{message}</p> : null}<div className="flex justify-end gap-3"><button type="button" onClick={() => setOpen(false)} className="min-h-10 px-3 text-sm font-semibold">Cancel</button><button type="button" disabled={pending || confirmation !== "DELETE"} onClick={remove} className="min-h-10 rounded-md bg-danger-strong px-4 text-sm font-semibold text-white disabled:opacity-50">Delete permanently</button></div></div></SheetContent></Sheet></> : null}{message ? <p role="alert" className="w-full text-sm text-danger-strong">{message}</p> : null}</div>;
}
