"use client";

import { ChevronRight, FileText, Plus, Video } from "lucide-react";
import { useState, useTransition } from "react";
import { Sheet, SheetContent, SheetDescription, SheetHeader, SheetTitle } from "@/components/ui/sheet";
import { saveSessionMaterialBlock } from "./actions";
import { isValidMaterialUrl, materialPreview } from "./model";
import type { MaterialBlockType, SessionMaterialBlock } from "./types";
import { RichTextEditor } from "./rich-text-editor";

type Draft = { id?: string; blockType: MaterialBlockType; title: string; richTextContent: Record<string, unknown>; url: string; description: string };
const emptyRichText = { type: "doc", content: [{ type: "paragraph" }] };

export function SessionMaterialEditor({ sessionId, blocks, archived }: { sessionId: string; blocks: SessionMaterialBlock[]; archived: boolean }) {
  const [drawer, setDrawer] = useState(false);
  const [draft, setDraft] = useState<Draft | null>(null);
  const [message, setMessage] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  function start(type: MaterialBlockType, block?: SessionMaterialBlock) { setMessage(null); setDraft(block ? { id: block.id, blockType: block.blockType, title: block.title ?? "", richTextContent: block.richTextContent ?? emptyRichText, url: block.url ?? "", description: block.description ?? "" } : { blockType: type, title: "", richTextContent: emptyRichText, url: "", description: "" }); setDrawer(false); }
  function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); if (draft?.blockType === "video_link" && !isValidMaterialUrl(draft.url)) { setMessage("Enter a valid http or https URL."); return; } const data = new FormData(event.currentTarget); data.set("sessionId", sessionId); if (draft?.id) data.set("blockId", draft.id); data.set("blockType", draft?.blockType ?? ""); data.set("richTextContent", JSON.stringify(draft?.richTextContent ?? emptyRichText)); startTransition(async () => { const result = await saveSessionMaterialBlock(data); if ("error" in result) setMessage(result.error); else { setDraft(null); setMessage("Material saved."); window.location.reload(); } }); }
  return <section className="mt-8 border-t border-border pt-6"><div className="flex flex-wrap items-start justify-between gap-3"><div><h2 className="font-heading text-xl font-bold text-text-primary">Session Material</h2><p className="mt-1 text-sm text-text-muted">Build and organize the material participants will use.</p></div>{!archived && !draft ? <button type="button" onClick={() => setDrawer(true)} className="inline-flex min-h-10 items-center gap-2 rounded-md bg-brand-primary px-4 py-2 text-sm font-semibold text-white"><Plus className="size-4" aria-hidden="true" />Add Content</button> : null}</div>{message && !draft ? <p role="status" className="mt-3 text-sm text-text-muted">{message}</p> : null}{draft ? <MaterialForm draft={draft} setDraft={setDraft} save={save} cancel={() => setDraft(null)} pending={pending} message={message} /> : blocks.length ? <div className="mt-5 grid gap-3">{blocks.map((block) => <div key={block.id} className="flex items-center justify-between gap-3 rounded-md border border-border bg-white p-4"><div className="min-w-0"><p className="text-xs font-semibold uppercase tracking-wide text-brand-secondary">{block.blockType === "rich_text" ? "Rich Text" : "Video / Link"}</p><p className="mt-1 truncate text-sm font-semibold text-text-primary">{materialPreview(block)}</p></div>{!archived ? <button type="button" onClick={() => start(block.blockType, block)} className="shrink-0 rounded-md px-3 py-2 text-sm font-semibold text-brand-primary hover:bg-surface-muted">Edit</button> : null}</div>)}</div> : <div className="mt-5 rounded-md border border-dashed border-border p-6 text-sm text-text-muted">No material has been added yet. Choose Add Content to begin.</div>}<Sheet open={drawer} onOpenChange={setDrawer}><SheetContent side="right" className="overflow-y-auto p-0"><SheetHeader className="border-b border-border px-6 py-5"><SheetTitle>Add Content</SheetTitle><SheetDescription>Choose the type of content to add.</SheetDescription></SheetHeader><div className="grid gap-3 p-6"><Chooser icon={<FileText className="size-5" />} title="Rich Text" description="Write article-style session material." onClick={() => start("rich_text")} /><Chooser icon={<Video className="size-5" />} title="Video / Link" description="Add a YouTube video or external link." onClick={() => start("video_link")} /></div></SheetContent></Sheet></section>;
}

function Chooser({ icon, title, description, onClick }: { icon: React.ReactNode; title: string; description: string; onClick: () => void }) { return <button type="button" onClick={onClick} className="flex items-center gap-3 rounded-md border border-border p-4 text-left hover:bg-surface-muted"><span className="text-brand-primary">{icon}</span><span className="min-w-0 flex-1"><span className="block text-sm font-semibold text-text-primary">{title}</span><span className="mt-1 block text-xs text-text-muted">{description}</span></span><ChevronRight className="size-4 text-text-muted" aria-hidden="true" /></button>; }

function MaterialForm({ draft, setDraft, save, cancel, pending, message }: { draft: Draft; setDraft: (draft: Draft) => void; save: (event: React.FormEvent<HTMLFormElement>) => void; cancel: () => void; pending: boolean; message: string | null }) { return <form className="mt-5 grid gap-4 rounded-md border border-border bg-white p-5" onSubmit={save}><p className="text-xs font-semibold uppercase tracking-wide text-brand-secondary">{draft.blockType === "rich_text" ? "Rich Text" : "Video / Link"}</p><label className="grid gap-1.5 text-sm font-medium">Title <input name="title" value={draft.title} onChange={(event) => setDraft({ ...draft, title: event.target.value })} maxLength={180} className="min-h-10 rounded-md border border-border px-3 text-sm" /></label>{draft.blockType === "rich_text" ? <RichTextEditor content={draft.richTextContent} onChange={(richTextContent) => setDraft({ ...draft, richTextContent })} /> : <><label className="grid gap-1.5 text-sm font-medium">URL <input name="url" required type="url" value={draft.url} onChange={(event) => setDraft({ ...draft, url: event.target.value })} placeholder="https://" className="min-h-10 rounded-md border border-border px-3 text-sm" /></label><label className="grid gap-1.5 text-sm font-medium">Description <textarea name="description" value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} rows={4} className="rounded-md border border-border px-3 py-2 text-sm" /></label></>}{message ? <p role="alert" className="text-sm text-danger-strong">{message}</p> : null}<div className="flex justify-end gap-3"><button type="button" onClick={cancel} disabled={pending} className="min-h-10 rounded-md px-3 py-2 text-sm font-semibold text-text-muted hover:bg-surface-muted">Cancel</button><button type="submit" disabled={pending} className="min-h-10 rounded-md bg-brand-primary px-4 py-2 text-sm font-semibold text-white disabled:opacity-60">{pending ? "Saving..." : "Save Block"}</button></div></form>; }
