import crypto from "node:crypto";
import { createClient } from "@supabase/supabase-js";
import { getSupabaseEnvironment } from "../lib/supabase/env.ts";

const DEV_PROJECT_REF = "lctkqjjkhpyootwvttvj";
const prefix = `verify-people-lifecycle-${Date.now()}`;
type Row = Record<string, unknown>;
function required(name: string) { const value = process.env[name]; if (!value) throw new Error(`Missing ${name}`); return value; }
function fail(error: { message: string } | null, action: string) { if (error) throw new Error(`${action}: ${error.message}`); }
function id(row: unknown, label: string) { const value = (row as Row | null)?.id; if (typeof value !== "string") throw new Error(`${label} id is missing`); return value; }

async function main() {
  const { url, publishableKey } = getSupabaseEnvironment(); if (new URL(url).hostname !== `${DEV_PROJECT_REF}.supabase.co`) throw new Error("People lifecycle verification refused outside approved DEV.");
  const service = createClient(url, required("SUPABASE_SECRET_KEY"), { auth: { autoRefreshToken: false, persistSession: false } });
  const cleanup = async () => { const result = await (service as unknown as { rpc(name: "cleanup_people_lifecycle_verifier_artifacts"): Promise<{ data: Record<string, number | string[]> | null; error: { message: string } | null }> }).rpc("cleanup_people_lifecycle_verifier_artifacts"); fail(result.error, "Clean protected lifecycle verifier history"); return result.data; };
  const existingCleanup = await cleanup(); const existingGroups = await service.from("groups").select("id").like("name", "verify-people-lifecycle-%"); fail(existingGroups.error, "Inspect lifecycle verifier artifacts before run"); if ((existingGroups.data ?? []).length) throw new Error(`Lifecycle verifier artifacts remain before run: ${JSON.stringify(existingCleanup)}`);
  const anon = createClient(url, publishableKey, { auth: { autoRefreshToken: false, persistSession: false } }); const anonCleanup = await (anon as unknown as { rpc(name: "cleanup_people_lifecycle_verifier_artifacts"): Promise<{ error: { message: string } | null }> }).rpc("cleanup_people_lifecycle_verifier_artifacts"); if (!anonCleanup.error) throw new Error("Anon unexpectedly executed lifecycle verifier cleanup");
  const authenticated = createClient(url, publishableKey, { auth: { autoRefreshToken: false, persistSession: false } }); fail((await authenticated.auth.signInWithPassword({ email: required("TEST_ADMIN_EMAIL").toLowerCase(), password: required("TEST_ADMIN_PASSWORD") })).error, "Sign in authenticated cleanup boundary fixture"); const authenticatedCleanup = await (authenticated as unknown as { rpc(name: "cleanup_people_lifecycle_verifier_artifacts"): Promise<{ error: { message: string } | null }> }).rpc("cleanup_people_lifecycle_verifier_artifacts"); if (!authenticatedCleanup.error) throw new Error("Authenticated user unexpectedly executed lifecycle verifier cleanup");
  const password = `Verify-${crypto.randomUUID()}!`; const userIds: string[] = []; const groupIds: string[] = []; let campusId = "";
  const createUser = async (label: string, role: string) => { const email = `${prefix}-${label.toLowerCase().replace(/[^a-z0-9]+/g, "-")}@example.test`; const created = await service.auth.admin.createUser({ email, password, email_confirm: true }); fail(created.error, `Create ${label} Auth`); const profileId = created.data.user?.id; if (!profileId) throw new Error(`Missing ${label} Auth id`); userIds.push(profileId); fail((await service.from("profiles").upsert({ id: profileId, campus_id: campusId, email, first_name: "Verify", last_name: label, status: "active" }, { onConflict: "id" })).error, `Create ${label} profile`); fail((await service.from("profile_roles").insert({ profile_id: profileId, role, assigned_by: profileId } as never)).error, `Create ${label} role`); return profileId; };
  const createGroup = async (groupType: "couple" | "coach_team" | "counselor_team" | "campus_lead_team", label: string, members = true) => { const created = await service.from("groups").insert({ name: `${prefix} ${label}`, group_type: groupType, campus_id: campusId }).select("id").single(); fail(created.error, `Create ${label} group`); const groupId = id(created.data, label); groupIds.push(groupId); if (members) { const role = groupType === "couple" ? "couple" : groupType === "coach_team" ? "coach" : groupType === "counselor_team" ? "counselor" : "campus_lead"; const [first, second] = await Promise.all([createUser(`${label}-one`, role), createUser(`${label}-two`, role)]); fail((await service.from("group_members").insert([{ group_id: groupId, profile_id: first }, { group_id: groupId, profile_id: second }])).error, `Create ${label} memberships`); } return groupId; };
  const removeAuth = async (ids: string[]) => { for (const userId of ids) { const removed = await service.auth.admin.deleteUser(userId); if (removed.error && !/not found/i.test(removed.error.message)) throw new Error(`Cleanup Auth: ${removed.error.message}`); } };
  let primaryFailure: unknown;
  try {
    const campus = await service.from("campuses").insert({ name: `${prefix} Campus`, code: prefix.slice(0, 48), active: true }).select("id").single(); fail(campus.error, "Create verifier campus"); campusId = id(campus.data, "Campus");
    for (const [type, label] of [["couple", "Couple"], ["coach_team", "Coach"], ["counselor_team", "Counselor"], ["campus_lead_team", "Campus Lead"]] as const) {
      const groupId = await createGroup(type, label); const deleted = await (service as unknown as { rpc(name: "delete_disposable_team_graph", args: { target_group_id: string }): Promise<{ data: { auth_user_ids?: string[] } | null; error: { message: string } | null }> }).rpc("delete_disposable_team_graph", { target_group_id: groupId }); fail(deleted.error, `Delete ${label} graph`); await removeAuth(deleted.data?.auth_user_ids ?? []); const remaining = await service.from("groups").select("id").eq("id", groupId); fail(remaining.error, `Verify ${label} group`); if ((remaining.data ?? []).length) throw new Error(`${label} group remained after transactional delete`); }
    const shellId = await createGroup("campus_lead_team", "Empty Shell", false); const shell = await (service as unknown as { rpc(name: "delete_disposable_team_graph", args: { target_group_id: string }): Promise<{ error: { message: string } | null }> }).rpc("delete_disposable_team_graph", { target_group_id: shellId }); fail(shell.error, "Delete empty shell");
    const pendingShell = await createGroup("couple", "Pending Invitation Shell", false); const inviter = await service.from("profiles").select("id").eq("email", required("TEST_ADMIN_EMAIL").toLowerCase()).maybeSingle(); fail(inviter.error, "Find verifier invitation owner"); const inviterId = id(inviter.data, "Verifier invitation owner"); const pendingAuthIds: string[] = [];
    for (const suffix of ["one", "two"]) { const email = `${prefix}-pending-${suffix}@example.test`; const created = await service.auth.admin.createUser({ email, password, email_confirm: true }); fail(created.error, `Create pending ${suffix} Auth`); const authUserId = id(created.data.user, `Pending ${suffix} Auth`); pendingAuthIds.push(authUserId); userIds.push(authUserId); fail((await service.from("invitations").insert({ email, first_name: "Pending", last_name: suffix, intended_role: "couple", campus_id: campusId, group_id: pendingShell, invited_by: inviterId, auth_user_id: authUserId } as never)).error, `Create pending ${suffix} invitation`); }
    const pendingDeleted = await (service as unknown as { rpc(name: "delete_disposable_team_graph", args: { target_group_id: string }): Promise<{ data: { auth_user_ids?: string[] } | null; error: { message: string } | null }> }).rpc("delete_disposable_team_graph", { target_group_id: pendingShell }); fail(pendingDeleted.error, "Delete pending invitation shell"); await removeAuth(pendingDeleted.data?.auth_user_ids ?? []); const pendingRemaining = await service.from("invitations").select("id").eq("group_id", pendingShell); fail(pendingRemaining.error, "Verify pending invitation cleanup"); if ((pendingRemaining.data ?? []).length) throw new Error("Pending invitation rows remained after shell delete");
    const protectedIntakeGroup = await createGroup("couple", "Protected Intake Shell", false); const intake = await service.from("intake_requests" as never).insert({ campus_id: campusId, relationship_status: "married", currently_working_with_counselor: false, requested_support: ["lay_counselor"], goals: "Lifecycle verifier protected intake", referral_source: "website", status: "invited", invited_group_id: protectedIntakeGroup } as never).select("id").single(); fail(intake.error, "Create protected intake"); const protectedIntakeId = id(intake.data, "Protected intake"); fail((await service.from("intake_request_people" as never).insert([{ intake_request_id: protectedIntakeId, person_position: "requester", first_name: "Verifier", last_name: "Requester", email: `${prefix}-intake-one@example.test`, phone: "+15555550101", city: "Test City" }, { intake_request_id: protectedIntakeId, person_position: "partner", first_name: "Verifier", last_name: "Partner", email: `${prefix}-intake-two@example.test`, phone: "+15555550102", city: "Test City" }] as never)).error, "Create protected intake people"); const intakeBlocked = await (service as unknown as { rpc(name: "delete_disposable_team_graph", args: { target_group_id: string }): Promise<{ error: { message: string } | null }> }).rpc("delete_disposable_team_graph", { target_group_id: protectedIntakeGroup }); if (!intakeBlocked.error?.message.includes("team_delete_blocker:intake_request_history")) throw new Error("Protected Intake shell did not report retained Intake Request history"); const intakeGroupRemaining = await service.from("groups").select("id").eq("id", protectedIntakeGroup); if ((intakeGroupRemaining.data ?? []).length !== 1) throw new Error("Protected Intake shell was partially deleted"); fail((await service.from("intake_requests" as never).update({ status: "ready_for_review", invited_group_id: null } as never).eq("id", protectedIntakeId)).error, "Unlink protected intake fixture"); fail((await service.from("intake_request_status_history" as never).delete().eq("intake_request_id", protectedIntakeId)).error, "Remove protected intake history"); fail((await service.from("intake_requests" as never).delete().eq("id", protectedIntakeId)).error, "Remove protected intake"); const intakeCleaned = await (service as unknown as { rpc(name: "delete_disposable_team_graph", args: { target_group_id: string }): Promise<{ error: { message: string } | null }> }).rpc("delete_disposable_team_graph", { target_group_id: protectedIntakeGroup }); fail(intakeCleaned.error, "Delete protected Intake shell after teardown");
    const protectedGroup = await createGroup("couple", "Protected"); const caseResult = await service.from("counseling_cases").insert({ campus_id: campusId, couple_group_id: protectedGroup, status: "requested" }).select("id").single(); fail(caseResult.error, "Create protected case"); const protectedCaseId = id(caseResult.data, "Protected case"); const blocked = await (service as unknown as { rpc(name: "delete_disposable_team_graph", args: { target_group_id: string }): Promise<{ error: { message: string } | null }> }).rpc("delete_disposable_team_graph", { target_group_id: protectedGroup }); if (!blocked.error) throw new Error("Protected team deletion was allowed"); const retained = await service.from("groups").select("id,group_members(id)").eq("id", protectedGroup).single(); fail(retained.error, "Verify protected rollback"); if (!retained.data || (retained.data.group_members ?? []).length !== 2) throw new Error("Protected team deletion partially mutated the graph"); const cleanupResult = await cleanup(); if (cleanupResult?.counseling_cases !== 1 || cleanupResult?.case_status_history !== 1) throw new Error(`Protected verifier cleanup did not remove exactly its case history: ${JSON.stringify(cleanupResult)}`); const caseRemaining = await service.from("counseling_cases").select("id").eq("id", protectedCaseId); fail(caseRemaining.error, "Verify protected case cleanup"); if ((caseRemaining.data ?? []).length) throw new Error("Protected verifier case remained after cleanup"); const cleaned = await (service as unknown as { rpc(name: "delete_disposable_team_graph", args: { target_group_id: string }): Promise<{ data: { auth_user_ids?: string[] } | null; error: { message: string } | null }> }).rpc("delete_disposable_team_graph", { target_group_id: protectedGroup }); fail(cleaned.error, "Delete protected fixture after rollback test"); await removeAuth(cleaned.data?.auth_user_ids ?? []);
    console.log("DEV People lifecycle transactional team deletion verification passed.");
  } catch (error) {
    primaryFailure = error;
  }
  let teardownFailure: unknown;
  try {
    await cleanup();
    for (const groupId of groupIds) { const result = await (service as unknown as { rpc(name: "delete_disposable_team_graph", args: { target_group_id: string }): Promise<{ data: { auth_user_ids?: string[] } | null; error: { message: string } | null }> }).rpc("delete_disposable_team_graph", { target_group_id: groupId }); if (!result.error) await removeAuth(result.data?.auth_user_ids ?? []); }
    await removeAuth(userIds); if (campusId) { const removed = await service.from("campuses").delete().eq("id", campusId); fail(removed.error, "Cleanup verifier campus"); }
    const remaining = await service.from("groups").select("id").like("name", `${prefix}%`); fail(remaining.error, "Verify verifier cleanup"); if ((remaining.data ?? []).length) throw new Error("Verifier-owned groups remained after cleanup");
  } catch (error) {
    teardownFailure = error;
  }
  if (primaryFailure && teardownFailure) throw new AggregateError([primaryFailure, teardownFailure], "Lifecycle verifier and teardown both failed");
  if (primaryFailure) throw primaryFailure;
  if (teardownFailure) throw teardownFailure;
}
await main();
