-- Kept separate from the enum extension above: PostgreSQL cannot safely use a new enum value until a later transaction.
alter table public.case_assignments alter column assigned_group_id drop not null, add column if not exists assigned_profile_id uuid references public.profiles(id) on delete restrict;
alter table public.case_assignments add constraint case_assignments_target_matches_type check ((assignment_type in ('coach', 'counselor') and assigned_group_id is not null and assigned_profile_id is null) or (assignment_type = 'campus_lead' and assigned_group_id is null and assigned_profile_id is not null));
create index case_assignments_active_profile_idx on public.case_assignments (assigned_profile_id, counseling_case_id) where ended_at is null and assigned_profile_id is not null;
create or replace function private.validate_case_assignment_group() returns trigger language plpgsql security definer set search_path = '' as $$ begin if new.assignment_type = 'campus_lead' then if new.assigned_group_id is not null or new.assigned_profile_id is null then raise exception 'Campus Lead assignments require an individual profile target'; end if; return new; end if; if new.assigned_profile_id is not null or not exists (select 1 from public.groups where id = new.assigned_group_id and active and group_type = case new.assignment_type when 'coach' then 'coach_team'::public.group_type when 'counselor' then 'counselor_team'::public.group_type end) then raise exception 'Assignment group type does not match assignment type'; end if; return new; end; $$;
create or replace function public.assign_counseling_case_as_campus_lead(target_case_id uuid, target_group_id uuid, target_assignment_type public.case_assignment_type, reassignment_reason text default 'Reassigned by Campus Lead') returns uuid language plpgsql security definer set search_path = '' as $$
declare actor uuid := auth.uid(); target_campus uuid; target_type public.group_type; new_assignment_id uuid;
begin
  if actor is null or not private.current_user_has_role(array['campus_lead']::public.app_role[]) then raise exception 'Only an active Campus Lead may use this assignment path'; end if;
  select campus_id into target_campus from public.counseling_cases where id = target_case_id for update;
  if target_campus is null or not private.current_user_oversees_campus(target_campus) then raise exception 'Counseling case is outside the Campus Lead scope'; end if;
  if target_assignment_type = 'campus_lead' then
    if target_group_id is not null or not exists (select 1 from public.profiles where id = actor and status = 'active') then raise exception 'Campus Lead self-assignment is not available'; end if;
    update public.case_assignments set ended_at = now(), end_reason = coalesce(nullif(btrim(reassignment_reason), ''), 'Reassigned by Campus Lead') where counseling_case_id = target_case_id and ended_at is null;
    insert into public.case_assignments (counseling_case_id, assigned_profile_id, assignment_type, assigned_by) values (target_case_id, actor, 'campus_lead', actor) returning id into new_assignment_id;
  else
    if target_assignment_type not in ('coach', 'counselor') then raise exception 'Unsupported assignment target'; end if;
    target_type := case target_assignment_type when 'coach' then 'coach_team'::public.group_type else 'counselor_team'::public.group_type end;
    if not exists (select 1 from public.groups where id = target_group_id and campus_id = target_campus and active and group_type = target_type) then raise exception 'Choose an active same-campus Coach or Counselor team'; end if;
    update public.case_assignments set ended_at = now(), end_reason = coalesce(nullif(btrim(reassignment_reason), ''), 'Reassigned by Campus Lead') where counseling_case_id = target_case_id and assignment_type = 'campus_lead' and ended_at is null;
    insert into public.case_assignments (counseling_case_id, assigned_group_id, assignment_type, assigned_by) values (target_case_id, target_group_id, target_assignment_type, actor) returning id into new_assignment_id;
  end if;
  update public.counseling_cases set status = 'matched' where id = target_case_id and status in ('requested', 'assessment', 'interviewed');
  insert into public.audit_events (actor_id,event_type,entity_type,entity_id,details) values (actor,'case.assigned','counseling_case',target_case_id,jsonb_build_object('assignment_id',new_assignment_id,'assignment_type',target_assignment_type,'group_id',target_group_id,'profile_id',case when target_assignment_type = 'campus_lead' then actor else null end)); return new_assignment_id;
end; $$;
revoke execute on function public.assign_counseling_case_as_campus_lead(uuid, uuid, public.case_assignment_type, text) from public, anon;
grant execute on function public.assign_counseling_case_as_campus_lead(uuid, uuid, public.case_assignment_type, text) to authenticated;
create or replace function private.current_user_can_access_case(target_case_id uuid) returns boolean language sql stable security definer set search_path = '' as $$
  select exists (select 1 from public.counseling_cases c where c.id = target_case_id and private.current_user_oversees_campus(c.campus_id)) or exists (select 1 from public.counseling_cases c join public.group_members m on m.group_id = c.couple_group_id and m.profile_id = auth.uid() and m.ended_at is null where c.id = target_case_id and private.current_user_has_role(array['couple']::public.app_role[])) or exists (select 1 from public.case_assignments a join public.group_members m on m.group_id = a.assigned_group_id and m.profile_id = auth.uid() and m.ended_at is null where a.counseling_case_id = target_case_id and a.ended_at is null and ((a.assignment_type = 'coach' and private.current_user_has_role(array['coach']::public.app_role[])) or (a.assignment_type = 'counselor' and private.current_user_has_role(array['counselor']::public.app_role[])))) or exists (select 1 from public.case_assignments a where a.counseling_case_id = target_case_id and a.assigned_profile_id = auth.uid() and a.assignment_type = 'campus_lead' and a.ended_at is null and private.current_user_has_role(array['campus_lead']::public.app_role[]));
$$;
